<?php

if (!function_exists('traduz')) {
    function traduz($termo)
    {
        // 1. Se o usuário não estiver logado OU a acessibilidade cognitiva estiver desligada
        // o sistema devolve a palavra original imediatamente.
        if (!auth()->check() || !auth()->user()->acessibilidade_cognitiva) {
            return $termo;
        }

        // 2. O Dicionário (Aqui você adiciona as palavras que quiser no futuro)
        $dicionario = [
           //'PCP' => 'TESTE FUNCIONOU',
           //'WMS' => 'Almoxarifado',
           //'MRP' => 'Cálculo de Compras',
           //'BOM' => 'Lista de Peças',
           //'SKU' => 'Código do Item',
           //'CRM' => 'Vendas',
           //'Lead Time' => 'Prazo de Entrega',
           //'Abrir vendas' => 'Realizar venda',
           
           // // PERFIL CORPORATIVO,
// 'Perfil Corporativo' => 'Informações da Empresa',
// 'Registro de Atividade Industrial' => 'Cadastro da Empresa',
// 'Monitor' => 'Acompanhar',
// 'PCP' => 'Planejamento da Produção',
// 'WMS' => 'Controle de Estoque',
// 'Expedição' => 'Envio de Produtos',
// 'Dados' => 'Informações',
// 'Resumo e Missão' => 'Sobre a Empresa',
// 'Número do CNPJ' => 'Número de Registro da Empresa',
// 'Contato Telefônico' => 'Telefone',
// 'Endereço da Unidade' => 'Endereço da Empresa',
// 'Unidade' => 'Empresa',
// 'Registro Eletrônico' => 'Registro no Sistema',
// 'Visualização restrita. Alterações apenas via Gerência (Professor).' => 'Você só pode ver. Apenas o professor pode alterar.',
//
// // GESTÃO À VISTA,
// 'Gestão à Vista' => 'Acompanhamento da Produção',
// 'Data Simulação' => 'Data do Jogo',
// 'Monitor de Produção em Tempo Real' => 'Acompanhar Produção Agora',
// 'Produto Acabado' => 'Produto Pronto',
// 'QTD' => 'Quantidade',
// 'Status' => 'Situação',
// 'Entrega' => 'Prazo de Entrega',
// 'Atrasado 9 dias' => 'Entrega atrasada há 9 dias',
// 'Arquivo Morto (Histórico Concluído)' => 'Pedidos Finalizados',
// 'Finalizado em' => 'Data de Conclusão',
// 'Concluído' => 'Finalizado',
//
// // DETALHES DO PEDIDO (POP-UP LOJA),
// 'Em Andamento' => 'Sendo Produzido',
// 'Arquivado' => 'Finalizado',
// 'Linha do Tempo de Suprimentos' => 'Etapas dos Materiais',
// 'SEQ.' => 'Ordem',
// 'Material' => 'Peça',
// 'Origem (Causa)' => 'Motivo',
// 'Status Atual' => 'Situação Atual',
// 'No Estoque' => 'Disponível no Estoque',
// 'PCP (Planejado)' => 'Planejado pela Produção',
// 'Produção (Reposição Estoque)' => 'Produzido para Repor Estoque',
// 'Produção (Refugo)' => 'Peça com Defeito (Refugo)',
// 'PED' => 'Pedido',
// 'OP' => 'Ordem de Produção',
// 'Vend' => 'Venda',
// 'Comp' => 'Compra',
// 'Prod' => 'Produção',
// 'Pack' => 'Embalagem',
// 'Exped' => 'Envio',
//
// // MÓDULO COMERCIAL / VENDAS,
// 'Módulo Comercial / Vendas' => 'Área de Vendas',
// 'Console de Operações Comerciais' => 'Painel de Vendas',
// 'Selecione o procedimento de trabalho' => 'Escolha o que deseja fazer',
// 'Abrir Vendas' => 'Criar Nova Venda',
// 'Registrar entrada de novo pedido de cliente' => 'Cadastrar novo pedido do cliente',
// 'Gerenciar Carteira' => 'Ver Meus Pedidos',
// 'Consultar status e histórico de pedidos ativos' => 'Ver situação e pedidos em andamento',
// 'Pedidos' => 'Pedidos feitos',
// 'Pendentes' => 'Aguardando',
// 'Menu Vendas' => 'Voltar para Vendas',
//
// // REGISTRO DE ORDEM DE VENDA,
// 'Registro de Ordem de Venda' => 'Cadastro de Pedido',
// 'Selecionar Cliente' => 'Escolher Cliente',
// 'Buscar na Carteira' => 'Procurar Cliente',
// 'Data de Entrega Prometida' => 'Data combinada para entrega',
// 'Data do Sistema' => 'Data de Hoje',
// 'Composição do Pedido' => 'Itens do Pedido',
// 'Produto / SKU' => 'Produto',
// 'Selecione o item' => 'Escolha o produto',
// 'QTD' => 'Quantidade',
// 'Adicionar Item' => 'Adicionar Produto',
// 'Finalizar Pedido' => 'Concluir Pedido',
// 'Cota de Vendas' => 'Meta de Vendas',
//
// // CARTEIRA DE PEDIDOS REALIZADOS,
// 'Carteira de Pedidos Realizados' => 'Lista de Pedidos',
// 'Parceiro Comercial' => 'Cliente',
// 'Data Emissão' => 'Data do Pedido',
// 'Data Entrega' => 'Data de Entrega',
// 'Valor Total' => 'Valor do Pedido',
// 'Status Operacional' => 'Situação do Pedido',
// 'Em Produção' => 'Sendo Produzido',
// 'Faturado' => 'Pago e Finalizado',
// 'Todos Clientes' => 'Todos os Clientes',
// 'Todos Status' => 'Todas as Situações',
// 'Aplicar' => 'Filtrar',
//
// // PAINEL DE CONTROLE - PCP,
// 'Painel de Controle - PCP' => 'Painel de Planejamento da Produção',
// 'Console de Planejamento e Controle' => 'Painel de Planejar e Controlar',
// 'Selecione o fluxo de análise' => 'Escolha o que deseja analisar',
// 'Vendas' => 'Pedidos de Venda',
// 'Análise de Demanda Bruta' => 'Análise de Pedidos Recebidos',
// 'Sem Pendências' => 'Nada Pendente',
// 'Produção' => 'Produzir',
// 'Gestão de Carga e Capacidade' => 'Controle da Capacidade de Produção',
// '1 OPs Ativas' => '1 Ordem de Produção em andamento',
// 'Suprimentos' => 'Materiais',
// 'Status de Abastecimento' => 'Situação do Estoque',
// '0 OCs Pendentes' => '0 Compras Pendentes',
// 'Menu PCP' => 'Voltar ao Planejamento',
//
// // ANÁLISE DE DEMANDA DE VENDAS,
// 'Análise de Demanda de Vendas' => 'Análise dos Pedidos de Venda',
// 'Data Prometida' => 'Data Combinada',
// 'Processamento' => 'Andamento',
// 'Sem novos pedidos na fila.' => 'Não há novos pedidos aguardando.',
// 'Cliente (Todos)' => 'Todos os Clientes',
// 'Produto (Todos)' => 'Todos os Produtos',
// 'Filtrar' => 'Aplicar Filtro',
//
// // STATUS GLOBAL DO CHÃO DE FÁBRICA,
// 'Status Global do Chão de Fábrica' => 'Situação Geral da Produção',
// 'OP' => 'Ordem de Produção',
// 'Quantidade' => 'Quantidade Produzida',
// 'Status Operacional' => 'Situação da Produção',
// 'Aberta' => 'Em Produção',
// 'Concluída' => 'Finalizada',
// 'Status (Todos)' => 'Todas as Situações',
// 'Filtrar' => 'Aplicar Filtro',
//
// // GESTÃO DE SUPRIMENTOS E ABASTECIMENTO,
// 'Gestão de Suprimentos e Abastecimento' => 'Controle de Materiais e Estoque',
// 'Buscar SKU/Nome' => 'Buscar Produto pelo Nome',
// 'OC' => 'Ordem de Compra',
// 'Material / Insumo' => 'Material',
// 'Volume' => 'Quantidade',
// 'Status' => 'Situação',
// 'Concluído' => 'Finalizado',
//
// // PAINEL DE COMPRAS & SUPRIMENTOS,
// 'Painel de Compras & Suprimentos' => 'Área de Compras e Materiais',
// 'Central de Aquisições' => 'Central de Compras',
// 'Gerencie o abastecimento' => 'Controle os materiais',
// 'Realizar Cotações' => 'Fazer Orçamento de Compra',
// 'Homologação e Compra' => 'Aprovar e Comprar',
// 'Nada Pendente' => 'Sem Pendências',
// 'Log de Ocorrências' => 'Registro de Problemas',
// 'Tratativa de Recusas' => 'Resolver Problemas de Entrega',
// 'Sem Problemas' => 'Tudo Certo',
// 'Histórico de Pedidos' => 'Pedidos Já Feitos',
// 'Rastreio de Entregas' => 'Acompanhar Entregas',
// 'A Caminho' => 'Em Transporte',
// 'Menu Compras' => 'Voltar para Compras',
//
// // NOVAS SOLICITAÇÕES (PCP),
// 'Novas Solicitações (PCP)' => 'Novos Pedidos de Compra',
// 'Prioridade' => 'Urgência',
// 'Item Solicitado' => 'Material Pedido',
// 'Volume Necessário' => 'Quantidade Necessária',
// 'Ação' => 'O que Fazer',
// 'Nenhuma Solicitação de Compra Pendente.' => 'Não há pedidos de compra pendentes.',
// 'Buscar material' => 'Procurar Material',
// 'Buscar' => 'Pesquisar',
//
// // OCORRÊNCIAS DE RECEBIMENTO,
// 'Ocorrências de Recebimento' => 'Problemas no Recebimento',
// 'Materiais Rejeitados pelo Almoxarifado (WMS)' => 'Materiais recusados no estoque',
// 'Fornecedor (Falha)' => 'Fornecedor com Problema',
// 'Material / Motivo da Recusa' => 'Material e Motivo da Recusa',
// 'Status Tratativa' => 'Situação do Problema',
// 'Resolvido' => 'Problema Resolvido',
// 'Fornecedor' => 'Empresa Fornecedora',
// 'Filtrar' => 'Aplicar Filtro',
//
// // RASTREIO DE PEDIDOS (COMPRAS ACEITAS),
// 'Rastreio de Pedidos (Compras Aceitas)' => 'Acompanhar Compras Aprovadas',
// 'OC ID' => 'Número da Compra',
// 'Material Comprado' => 'Material',
// 'Fornecedor' => 'Empresa Fornecedora',
// 'Previsão Entrega' => 'Data Prevista de Entrega',
// 'Status Logístico' => 'Situação da Entrega',
// 'Status (Todos)' => 'Todas as Situações',
//
// // WMS - RECEBIMENTO E ARMAZENAGEM,
// 'WMS - Recebimento e Armazenagem' => 'Estoque - Receber e Guardar Materiais',
// 'Checklist de Entrada (Conferência)' => 'Lista de Verificação na Entrada',
// 'Pátio Limpo' => 'Sem Caminhões Aguardando',
// 'Nenhum caminhão aguardando descarga no momento.' => 'Não há caminhões esperando para descarregar.',
// 'Status da Doca' => 'Situação da Área de Descarga',
// 'Doca Livre' => 'Área de Descarga Livre',
// 'Aguardando próximas compras' => 'Esperando novas entregas',
// 'Procedimento Padrão' => 'Passo a Passo',
// 'Confira a quantidade física contra a OC.' => 'Verifique se a quantidade recebida está igual ao pedido de compra.',
// 'Se houver avaria, clique em 'Recusar'.' => 'Se estiver com problema, clique em 'Recusar'.',
// 'Material recebido fica no 'chão' para endereçamento.' => 'O material recebido fica aguardando para ser guardado no estoque.',
// 'Ver Inventário' => 'Ver Estoque',
// 'Abrir Mapa WMS' => 'Abrir Mapa do Estoque',
// 'Pedidos da Produção (Picking)' => 'Pedidos da Produção para Separar',
// 'Atender solicitações do chão de fábrica' => 'Separar materiais pedidos pela produção',
// 'Pendentes' => 'Aguardando',
//
// // CONSULTA DE INVENTÁRIO,
// 'Consulta de Inventário' => 'Consultar Estoque',
// 'Estoque Atual' => 'Estoque Disponível',
// 'Buscar por Nome ou SKU' => 'Buscar pelo Nome do Produto',
// 'SKU (Código)' => 'Código do Produto',
// 'Material / Insumo' => 'Material',
// 'Endereço (WMS)' => 'Local no Estoque',
// 'Saldo Físico' => 'Quantidade Disponível',
// 'Voltar ao Pátio' => 'Voltar para Recebimento',
// 'Buscar' => 'Pesquisar',
//
// // MAPA DE ARMAZENAGEM (WMS),
// 'Mapa de Armazenagem (WMS)' => 'Mapa do Estoque',
// 'Rua' => 'Corredor',
// 'Coluna' => 'Prateleira',
// 'Guardar Aqui' => 'Guardar Neste Local',
//
// // FILA DE SEPARAÇÃO (PICKING LIST),
// 'Fila de Separação (Picking List)' => 'Lista de Separação',
// 'OP Ref.' => 'Ordem de Produção',
// 'Produto Final' => 'Produto Pronto',
// 'Material Solicitado' => 'Material Pedido',
// 'Qtd. a Separar' => 'Quantidade para Separar',
// 'Ação' => 'O que Fazer',
// 'Localizar' => 'Encontrar no Estoque',
//
// // AÇÃO NECESSÁRIA: PICKING,
// 'Ação Necessária: Picking' => 'Ação Necessária: Separar Material',
// 'Localize o endereço piscando e retire:' => 'Encontre o local destacado e retire:',
//
// // CHÃO DE FÁBRICA - PRODUÇÃO,
// 'Chão de Fábrica - Produção' => 'Área de Produção',
// 'Voltar ao Menu' => 'Voltar',
// 'Ordens Disponíveis (Backlog)' => 'Ordens Disponíveis para Produzir',
// 'Backlog' => 'Ordens na Fila',
// 'Linha Limpa' => 'Sem Ordens na Fila',
// 'Nenhuma ordem aguardando produção.' => 'Não há ordens esperando para produzir.',
// 'Linhas de Produção Ativas' => 'Linhas Produzindo',
// 'Sua Carga' => 'Seu Limite de Ordens',
// 'Linha de:' => 'Linha do Operador:',
// 'Sua Linha' => 'Minha Linha',
// 'Aberta' => 'Em Produção',
// 'Qtd:' => 'Quantidade:',
// 'Aguardando WMS' => 'Aguardando Material do Estoque',
//
// // QUALIDADE & REFUGO,
// 'Qualidade & Refugo' => 'Qualidade e Perdas',
// 'Acessar histórico de apontamentos e perdas.' => 'Ver histórico de produção e perdas.',
// 'Acessar Relatório' => 'Ver Relatório',
//
// // HISTÓRICO DE PRODUÇÃO,
// 'Histórico de Produção' => 'Produção Realizada',
// 'Data/Hora' => 'Data',
// 'OP' => 'Ordem de Produção',
// 'Operador' => 'Funcionário',
// 'Produzido' => 'Quantidade Produzida',
// 'Refugo' => 'Peças com Defeito',
// 'Filtrar' => 'Aplicar Filtro',
// 'Voltar para a Linha' => 'Voltar para Produção',
//
// // ESTAÇÃO DE EMBALAGEM,
// 'Estação de Embalagem' => 'Área de Embalar Produtos',
// 'Voltar' => 'Voltar ao Menu',
// 'Linha de Empacotamento Ativa' => 'Linha de Embalagem Funcionando',
// 'Nenhum lote na esteira' => 'Nenhum produto para embalar',
// 'Aguardando a conclusão de ordens na Produção.' => 'Aguardando a produção terminar para embalar',
//
// // EXPEDIÇÃO E FATURAMENTO,
// 'Expedição e Faturamento' => 'Envio e Emissão de Nota',
// 'Terminal de Saída (Outbound)' => 'Área de Envio de Produtos',
// 'Gerencie o embarque e faturamento' => 'Controle o envio e a emissão de notas',
// 'Dock de Saída' => 'Área de Envio',
// 'Conferência e Emissão de NF' => 'Conferir e Emitir Nota Fiscal',
// 'Doca Vazia' => 'Área de Envio Vazia',
// 'Histórico de NFs' => 'Notas Fiscais Emitidas',
// 'Arquivo Morto Fiscal' => 'Notas Fiscais Antigas',
// 'Notas Emitidas' => 'Notas Criadas',
// 'Menu Expedição' => 'Voltar para Envio',
//
// // PEDIDOS AGUARDANDO EMBARQUE,
// 'Pedidos Aguardando Embarque' => 'Pedidos Esperando Envio',
// 'Pedido #' => 'Número do Pedido',
// 'Cliente / Destino' => 'Cliente e Destino',
// 'Volumes' => 'Quantidade de Caixas',
// 'Valor Carga' => 'Valor do Pedido',
// 'Status Prazo' => 'Situação do Prazo',
// 'Ação' => 'O que Fazer',
// 'Doca vazia. Nenhum pedido liberado pela Produção.' => 'Nenhum pedido pronto para envio.',
// 'Todos Clientes' => 'Todos os Clientes',
// 'Filtrar' => 'Aplicar Filtro',
//
// // ARQUIVO FISCAL (NFS EMITIDAS),
// 'Arquivo Fiscal (NFs Emitidas)' => 'Lista de Notas Fiscais Emitidas',
// 'NF-e Nº' => 'Número da Nota Fiscal',
// 'Emissão' => 'Data de Emissão',
// 'Cliente' => 'Cliente',
// 'Valor Total' => 'Valor da Nota',
// 'Chave de Acesso' => 'Código da Nota Fiscal',
// 'NF ou Cliente...' => 'Buscar por Número da Nota ou Cliente',
// 'Buscar' => 'Pesquisar',
//
// // CADASTRO DE MATÉRIAS-PRIMAS (ALUNO),
// 'Cadastro de Matérias-Primas (Aluno)' => 'Cadastro de Materiais (Aluno)',
// 'Cadastrar Novo Material' => 'Adicionar Novo Material',
// 'SKU (Código)' => 'Código do Material',
// 'Nome do Insumo' => 'Nome do Material',
// 'Unidade' => 'Unidade de Medida',
// 'Salvar' => 'Guardar',
// 'Materiais Cadastrados' => 'Lista de Materiais',
// 'SKU' => 'Código',
// 'Nome' => 'Nome do Material',
//
// // CADASTRO DE CLIENTES,
// 'Meus Clientes' => 'Clientes',
// 'Cadastrar Novo Cliente' => 'Adicionar Novo Cliente',
// 'Nome / Razão Social' => 'Nome do Cliente',
// 'CNPJ / CPF' => 'Documento (CPF ou CNPJ)',
// 'Telefone' => 'Número de Telefone',
// 'Localização' => 'Endereço',
// 'CEP' => 'CEP (Código Postal)',
// 'Rua' => 'Nome da Rua',
// 'Número' => 'Número do Endereço',
// 'Bairro' => 'Bairro',
// 'Cidade' => 'Cidade',
// 'UF' => 'Estado',
// 'Cadastrar Cliente' => 'Salvar Cliente',
// 'Clientes da Minha Empresa' => 'Lista de Clientes',
// 'Nome / Razão' => 'Nome do Cliente',
// 'Documento' => 'CPF ou CNPJ',
// 'Localização' => 'Cidade e Estado',
//
// // CADASTRO DE FORNECEDORES,
// 'Meus Fornecedores' => 'Fornecedores',
// 'Cadastrar Novo Fornecedor' => 'Adicionar Novo Fornecedor',
// 'Nome / Razão Social' => 'Nome do Fornecedor',
// 'CNPJ / CPF' => 'Documento (CPF ou CNPJ)',
// 'Telefone' => 'Número de Telefone',
// 'Dados Comerciais' => 'Informações de Venda',
// 'Material Fornecido' => 'Material Vendido',
// 'Preço Unitário (R$)' => 'Preço por Unidade',
// 'Prazo Entrega (Dias)' => 'Prazo de Entrega (em dias)',
// 'Endereço' => 'Endereço do Fornecedor',
// 'CEP' => 'CEP (Código Postal)',
// 'Rua' => 'Nome da Rua',
// 'Número' => 'Número do Endereço',
// 'Bairro' => 'Bairro',
// 'Cidade' => 'Cidade',
// 'Estado (UF)' => 'Estado',
// 'Salvar Fornecedor' => 'Guardar Fornecedor',
// 'Fornecedores da Minha Empresa' => 'Lista de Fornecedores',
// 'Fornecedor' => 'Nome do Fornecedor',
// 'Especialidade' => 'Material Vendido',
// 'Preço' => 'Preço por Unidade',
// 'Prazo' => 'Prazo de Entrega',
//
// // MINHA CONTA,
// 'Minha Conta' => 'Meu Perfil',
// 'Voltar' => 'Voltar ao Menu',
// 'Aluno Operador' => 'Aluno',
//
// // ATUALIZAR SENHA,
// 'Atualizar Senha' => 'Trocar Senha',
// 'Garante que sua conta esteja usando uma senha longa e aleatória para se manter segura.' => 'Use uma senha forte para proteger sua conta.',
// 'Senha Atual' => 'Senha de Agora',
// 'Nova Senha' => 'Nova Senha',
// 'Confirmar Senha' => 'Digite a Nova Senha Novamente',
// 'Salvar' => 'Guardar Nova Senha',
// 'Para alterações de e-mail ou exclusão de conta, contate o administrador.' => 'Para mudar e-mail ou excluir conta, fale com o professor.',
//
// // PORTARIA / RECEPÇÃO,
// 'Portaria / Recepção' => 'Entrada da Fábrica',
//
// // ACESSO AUTORIZADO,
// 'Acesso Autorizado' => 'Entrada Permitida',
// 'Identificação: Joao' => 'Usuário: Joao',
// 'Bem-vindo à Fábrica Digital!' => 'Bem-vindo ao Sistema!',
// 'Seu cadastro foi realizado com sucesso, mas você ainda não possui um posto de trabalho definido.' => 'Seu cadastro foi feito, mas você ainda não tem uma função definida.',
// 'Aguarde enquanto o Game Master (Professor) escala você em uma Turma e define seu Setor (Vendas, Produção, etc).' => 'Espere o professor colocar você em uma turma e escolher seu setor (Vendas, Produção e outros).',
// 'Verificar Novamente' => 'Atualizar Página',
// 'Sistema de Gestão Industrial Integrada V1.5' => 'Sistema da Fábrica - Versão 1.5',


           
        ];

        // 3. Procura no dicionário: Se achar, traduz. Se não, mostra o original.
        return $dicionario[$termo] ?? $termo;
    }
}